FROM python:3.11
WORKDIR /app

COPY backend/requirements.txt backend/backend.py backend/.flaskenv ./
RUN pip install --no-cache-dir -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "backend:app"]